#!/bin/bash

# Generate frontend config.js from CloudFormation outputs
# Usage: ./generate-frontend-config.sh <stack-name> <region> <profile>

set -e

STACK_NAME=$1
REGION=$2
PROFILE=$3

if [ -z "$STACK_NAME" ] || [ -z "$REGION" ] || [ -z "$PROFILE" ]; then
    echo "Usage: $0 <stack-name> <region> <profile>"
    exit 1
fi

echo "Fetching CloudFormation outputs..."

# Get stack outputs
API_ENDPOINT=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --profile "$PROFILE" \
    --query 'Stacks[0].Outputs[?OutputKey==`APIEndpoint`].OutputValue' \
    --output text)

USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --profile "$PROFILE" \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
    --output text)

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --profile "$PROFILE" \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
    --output text)

if [ -z "$API_ENDPOINT" ] || [ -z "$USER_POOL_ID" ] || [ -z "$USER_POOL_CLIENT_ID" ]; then
    echo "Error: Could not retrieve all required outputs from CloudFormation"
    exit 1
fi

echo "Generating config.js..."

cat > frontend/js/config.js << EOF
// Auto-generated configuration from CloudFormation outputs
// Generated on: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
// DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-frontend-config.sh instead

const CONFIG = {
    API_ENDPOINT: '${API_ENDPOINT}',
    COGNITO_USER_POOL_ID: '${USER_POOL_ID}',
    COGNITO_CLIENT_ID: '${USER_POOL_CLIENT_ID}',
    COGNITO_REGION: '${REGION}'
};
EOF

echo "✅ Config file generated successfully at frontend/js/config.js"
echo ""
echo "Configuration:"
echo "  API Endpoint:     $API_ENDPOINT"
echo "  User Pool ID:     $USER_POOL_ID"
echo "  Client ID:        $USER_POOL_CLIENT_ID"
echo "  Region:           $REGION"
