// Auto-generated configuration from CloudFormation outputs
// Generated on: 2026-03-19T18:38:10Z
// DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-frontend-config.sh instead

const CONFIG = {
    API_ENDPOINT: 'https://dz4swpkxrd.execute-api.us-west-2.amazonaws.com/prod',
    COGNITO_USER_POOL_ID: 'us-west-2_BlXSbgm7X',
    COGNITO_CLIENT_ID: '25n9ls77job173jsh1geesvilv',
    COGNITO_REGION: 'us-west-2'
};
