// Auto-generated configuration from CloudFormation outputs
// Generated on: 2026-03-23T12:59:47Z
// DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-frontend-config.sh instead

const CONFIG = {
    API_ENDPOINT: 'https://ud3qxzm1wa.execute-api.us-east-2.amazonaws.com/prod',
    COGNITO_USER_POOL_ID: 'us-east-2_stpcviV7U',
    COGNITO_CLIENT_ID: '753uibvtlg7u4s6r2ks0k8sgiv',
    COGNITO_REGION: 'us-east-2'
};
