// Auto-generated configuration from CloudFormation outputs
// Generated on: 2026-03-23T12:59:47Z
// DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-frontend-config.sh instead

const CONFIG = {
    API_ENDPOINT: '',
    COGNITO_USER_POOL_ID: '',
    COGNITO_CLIENT_ID: '',
    COGNITO_REGION: ''
};
